# https://docs.fedoraproject.org/en-US/fedora-server/usecase-gui-addon/

- name: Install LXDE
  ansible.builtin.dnf:
    name:
      - @lxde-desktop-environment
    state: latest
  become: true

- name: Install GDM
  ansible.builtin.dnf:
    name:
      - gdm
    state: latest
  become: true
  notify: reboot
  when: GDM

# https://stackoverflow.com/questions/64701241/how-do-i-write-ansible-task-for-systemctl-set-default-graphical-target-without
- name: Get current systemd default
  command: "systemctl get-default"
  changed_when: false
  register: systemdefault

- name: Set default to graphical target
  command: "systemctl set-default graphical.target"
  when: "'graphical' not in systemdefault.stdout"
  become: true

- name: Enable GDM - systemctl enable gdm.service
  ansible.builtin.systemd_service:
    name: gdm.service
    state: started
    enabled: true
  become: true
  notify: reboot
  when: GDM